version: "3.8"
services:
  app:
    image: koko-assignment:main
    ports:
      - "5000:5000"
    command: gunicorn --bind 0.0.0.0:5000 app:app
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 10s
